In [24]:
import torch

x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [25]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [26]:
print(y.grad_fn)
print(dir(y.grad_fn))
print(y.grad_fn.metadata)
print(y.grad_fn.name)

['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_register_hook_dict', 'metadata', 'name', 'next_functions', 'register_hook', 'requires_grad']
{}
<built-in method name of AddBackward0 object at 0x11adc5dd8>


In [30]:
z = y * y * 3
print(z)
out = z.mean()
print(z, out)
a = torch.tensor([[1.,2.],[3., 4.]], requires_grad=True)
a_mean = a.mean()
print(a, a_mean)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)
tensor([[1., 2.],
        [3., 4.]], requires_grad=True) tensor(2.5000, grad_fn=<MeanBackward1>)


In [28]:
out.backward()
a_mean.backward()

In [31]:
print(x.grad)
print(a.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
None


In [34]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([-178.3352, 1010.7505,  673.6302], grad_fn=<MulBackward0>)


In [35]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])
